// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function CopyAction() {
  return window['go']['main']['App']['CopyAction']();
}

export function CutAction() {
  return window['go']['main']['App']['CutAction']();
}

export function ExtractFilePath(arg1) {
  return window['go']['main']['App']['ExtractFilePath'](arg1);
}

export function ExtractFilePaths(arg1) {
  return window['go']['main']['App']['ExtractFilePaths'](arg1);
}

export function GetAppTitle() {
  return window['go']['main']['App']['GetAppTitle']();
}

export function GetLastDirectory() {
  return window['go']['main']['App']['GetLastDirectory']();
}

export function GetOpenedFilePath() {
  return window['go']['main']['App']['GetOpenedFilePath']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetStaticHTML() {
  return window['go']['main']['App']['GetStaticHTML']();
}

export function HandleFileDrop(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleFileDrop'](arg1, arg2, arg3);
}

export function HasUnsavedChanges() {
  return window['go']['main']['App']['HasUnsavedChanges']();
}

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function LoadHTMLFile(arg1) {
  return window['go']['main']['App']['LoadHTMLFile'](arg1);
}

export function MarkFileAsSaved(arg1) {
  return window['go']['main']['App']['MarkFileAsSaved'](arg1);
}

export function MarkFileAsUnsaved(arg1) {
  return window['go']['main']['App']['MarkFileAsUnsaved'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function PasteAction() {
  return window['go']['main']['App']['PasteAction']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function ProxyURL(arg1) {
  return window['go']['main']['App']['ProxyURL'](arg1);
}

export function QueryOpenRouter(arg1, arg2) {
  return window['go']['main']['App']['QueryOpenRouter'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RedoAction() {
  return window['go']['main']['App']['RedoAction']();
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function RequestClose() {
  return window['go']['main']['App']['RequestClose']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveFileUnder(arg1, arg2) {
  return window['go']['main']['App']['SaveFileUnder'](arg1, arg2);
}

export function SetAppTitle(arg1) {
  return window['go']['main']['App']['SetAppTitle'](arg1);
}

export function SetUnsavedChanges(arg1) {
  return window['go']['main']['App']['SetUnsavedChanges'](arg1);
}

export function UndoAction() {
  return window['go']['main']['App']['UndoAction']();
}
