// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentFile(arg1:string):Promise<string>;

export function ClearRecentFiles():Promise<string>;

export function CloseApp():Promise<void>;

export function CopyAction():Promise<void>;

export function CutAction():Promise<void>;

export function ExtractFilePath(arg1:string):Promise<string>;

export function ExtractFilePaths(arg1:string):Promise<Array<string>>;

export function GetAppTitle():Promise<string>;

export function GetLastDirectory():Promise<string>;

export function GetOpenedFilePath():Promise<string>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetStaticHTML():Promise<string>;

export function HandleFileDrop(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;

export function HasUnsavedChanges():Promise<boolean>;

export function HomeDir():Promise<string>;

export function ListDir(arg1:string):Promise<Array<Record<string, any>>>;

export function LoadFile():Promise<main.FileResult>;

export function LoadHTMLFile(arg1:string):Promise<string>;

export function MarkFileAsSaved(arg1:string):Promise<void>;

export function MarkFileAsUnsaved(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function PasteAction():Promise<void>;

export function Ping(arg1:string):Promise<string>;

export function ProxyURL(arg1:string):Promise<string>;

export function QueryOpenRouter(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RedoAction():Promise<void>;

export function RemoveRecentFile(arg1:string):Promise<string>;

export function RequestClose():Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;

export function SaveFileUnder(arg1:string,arg2:string):Promise<string>;

export function SetAppTitle(arg1:string):Promise<void>;

export function SetUnsavedChanges(arg1:boolean):Promise<void>;

export function UndoAction():Promise<void>;
